### PR TITLE
Create endpoint to connect/disconnect local users with sociallogin via api

### PR DESCRIPTION
**Pull request by to-kn**
since i dont have direct access to the nextcloud db, i need a way to link existing users to their sociallogin via api

### CODE REVIEW

**Comment by zorn-v** [comment]
You should pass `identifier` (from provider) to `disconnectLogin`, not uid.
Also not PSR formatted :smile: 

I'll fix it

**Comment by to-kn** [comment]
Thanks a lot! 🎉

**Comment by zorn-v** [comment]
Also changed `$login` to `$identifier` in connect for consistency

**Comment by to-kn** [comment]
jep, sry i missed that - will you create a minor release for it? Would be wonderfull :)

**Pull request merged**
