### PR TITLE
Update user profile on login

### PR DESCRIPTION
**Pull request by Matthijsy**
Hi,

I found out that the user profile data was only loaded on the first login. This can for example cause issues when a user updates his profile picture or email adres. This PR suggests an update to make sure that this data is always reloaded. 

I would like to receive feedback what you all think about this and if I could improve the code

### CODE REVIEW

**Comment by zorn-v** [comment]
I specifically made getting oauh profile info only on account create. User can change it in profile settings. I don't think if they changed on next login is good idea. 
Also you forgot about one account with many connected oauth profiles.

**Comment by Matthijsy** [comment]
Okay, can understand that usecase. We have a project in which we have an oauth provider that keeps al the data and then use different other applications which should use the same data (of which nextcloud would be one). In that case an update on login would be useful. (then we don't need to update en email adres in all the systems for example). Would it be an idea to make this optional?

**Comment by zorn-v** [comment]
Maybe some checkbox (disabled by default) in admin settings section ?

**Comment by Matthijsy** [comment]
I've added an checkbox (which is disabled by default) to be able to control this behaviour

**Pull request merged**
