### PR TITLE
add User identifier for custom OAuth2

### PR DESCRIPTION
**Pull request by tomaszduda23**
Adds identifier that will be used to create an account for the authenticated user. Retrieved from the resource server specified via the Profile url field. Before only fixed hardcoded values were possible.

E.g. in case of Gitea
curl -u test:testtest 'https://test.com/api/v1/user?'
response looks like this
{"id":1,"login":"test","full_name":"","email":"test@test.com","avatar_url":"https://test.com/user/avatar/test/-1","language":"en-US","is_admin":false,"last_login":"2021-03-10T22:19:27+01:00","created":"2021-03-10T22:19:11+01:00","username":"test"}
so "gitea-1" had to be used as user name before. Now it is possible to use "username" or "login" which translates to "gitea-test".

### CODE REVIEW

**Comment by zorn-v** [comment]
It is not safe as chosen field may be not unique. This field must be hardcoded.

**Comment by tomaszduda23** [comment]
@zorn-v this PR provide more flexibility for custom oauth2. Admin has to make sure that the filed will be unique. portainer does exactly the same thing.
Could you please reconsider this?

https://github.com/portainer/portainer/blob/da29c2b6a5fdf9715c3a8c3680a3214bf3bc3e6b/app/portainer/oauth/components/oauth-settings/oauth-settings.html#L114

**Comment by zorn-v** [comment]
I don't care how it's done somewhere else. OAuth is not trusted source, so must be restricted as much possible

**Comment by tomaszduda23** [comment]
Take a look in the history of this code: "Another workaround for custom oauth2 ", "Workaround for custom oauth id", etc. I could add another workaround but it does not make sense. PR allows for flexibility. Does OAuth specify those hardcoded values? It looks that it does not. So how many values are you going to hardcode?

Nextcloud's admin can decided if and how it should be used. If someone does not like it the filed can be empty to get legacy behavior. If you don't like flexibility why do you support custom OAuth at all? Now it just happen to work with some providers and it does not work with the others.

**Comment by zorn-v** [comment]
> So how many values are you going to hardcode?

It not so many as you think.

> why do you support custom OAuth at all?

I don't know :smile: 
Honestly, I was not want to accept those PR which bring it.

**Pull request closed without merging**
