### PR TITLE
docs: Describe configuration for discord

### PR DESCRIPTION
**Pull request by pktiuk**
Linked with: https://github.com/zorn-v/nextcloud-social-login/issues/352

### CODE REVIEW

**Comment by zorn-v** [comment]
What a problem ?
If you know how describe spep by step - just do it.

If you just want to point to missed doc, then what point in your message ?

**Comment by pktiuk** [comment]
@zorn-v   This is a PR, I just described config step by step, and now I am submitting this piece of docs to codebase.

**Comment by zorn-v** [comment]
UPS. Sorry, considered as another issue "need help" :)

**Comment by pktiuk** [comment]
No problem.   
Anyway, thanks for great app :)

**Comment by zorn-v** [comment]
You are welcome. Opensource rulezz )

**Pull request merged**
