### PR TITLE
Add Slack as preconfigured OAuth provider

### PR DESCRIPTION
**Pull request by cboehme**
This is a companion pull request for a pull request hybridauth/hybridauth#1130 in the hybridauth repository. It builds on the Slack provider added to hybridauth by the other pull request and makes it available in nextcloud-social-login. 

It makes only sense to apply this pull request after hybridauth has excepted the other pull request and the dependency in nextcloud-social-plugin is updated.

### CODE REVIEW

**Comment by zorn-v** [comment]
In such cases we can do exceptions. I did it with amazon provider )

**Comment by zorn-v** [comment]
Just copy your class to proper vendor dir and I will be know about it

**Comment by cboehme** [comment]
Sorry for the late reply. I was away over Christmas. I pushed another commit which adds the slack-provider to the hybridauth copy in the 3rd-party folder.

**Comment by zorn-v** [comment]
Why you change TwichTV ? )
But never mind

**Comment by cboehme** [comment]
There was a bug in the Collection class, which I needed to fix as I wanted to use the broken method. Fixing the bug properly required a breaking change in Collection. So, I had to update all other providers which also used the method. Luckily, the Twitch TV provider was the only one.

**Comment by zorn-v** [comment]
Why just do not use buggy method ? It is not related to adding slack provider. I mean original PR to hybridauth.

**Comment by cboehme** [comment]
Of course, I could have implemented the slack provider without using the `Collection` class at all. But then, what's the point of having utility classes such as `Collection` if you do not use them because they are buggy?
As I consider it good practise to fix bugs when you see them instead of applying workarounds, I decided to fix the bug in `Collection` so that I could use the class in the slack provider subsequently. 
To make clear that this change is unrelated to adding the slack provider (while the slack provider still depends on it!) I made it a separate commit in the PR branch.

**Comment by zorn-v** [comment]
Best practice is do bugfix in separate pull request :wink:

**Pull request merged**
