### PR TITLE
Add support for Discourse

### PR DESCRIPTION
**Pull request by paroga**
There is a [PR for the `Hybridauth` changes](https://github.com/hybridauth/hybridauth/pull/1293), but since there is no response since over a month it would be nice, if we could adapt it here already.

### CODE REVIEW

**Comment by paroga** [comment]
@zorn-v any chance to get this into `master`?

**Comment by zorn-v** [comment]
I think no. Another "custom" for one provider. Are you kidding ?

**Comment by paroga** [comment]
no, i'm not kidding. discourse is a very popular project and as you see with #263 and my older [`user_discourse`](https://github.com/paroga/user_discourse) app people want to connect with it. IMHO this app would be a good fit for sharing the code, since it provides already everything required for integrating with nextcloud.
i don't get your negative attitude towards this PR, since the changes in `ProviderService.php` are minimal.

**Comment by zorn-v** [comment]
I don't like "non standard" implementation, but maybe I'm wrong.
Is discourse does not provides more standartized way like OpenID connect ?

**Comment by paroga** [comment]
> I don't like "non standard" implementation, but maybe I'm wrong.

I do not like them too, but unfortunately Discourse does not provide a standardized way. I support your statement that adding non-standard implementations is wrong, but we do not live in a perfect world where everything uses the latest standards and backward-compatibility can be ignored. Sometimes a pragmatic solution is a "better" solution regarding usability.

Adding a __secure__ OpenID implementation to Discourse is not an easy task. Compared to that, the changes in this app are straight forward and I think adding my code to your app, is a better way to offer Discourse support for end-users, than via a separate app, where 95% of the code for integrating into Nextcloud is very similar (if not the same).

**Comment by zorn-v** [comment]
> but we do not live in a perfect world

Agree. Well, let's do some changes then.
1. Move `Discourse` class from hybridauth lib. Seems it will not be merged there, but maybe I will need to update that lib.
2. Rename `sso_secret` to `secret` as in other providers. (at least in provider class config)
3. Remove `api_key` from mapping (did not find that it used)
4. Remove compiled `settings.js` - it is already outdated in this PR, I'll compile it after merge.
5. Rebase to master

**Comment by zorn-v** [comment]
So "no" means "no"

**Pull request closed without merging**
